<?php
namespace Mustache;

/*
 * This file is part of Mustache.php.
 *
 * (c) 2010-2014 Justin Hileman
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Mustache Cache interface.
 *
 * Interface for caching and loading \Mustache\Template classes
 * generated by the \Mustache\Compiler.
 */
interface Cache
{
    /**
     * Load a compiled \Mustache\Template class from cache.
     *
     * @param string $key
     *
     * @return boolean indicates successfully class load
     */
    public function load($key);

    /**
     * Cache and load a compiled \Mustache\Template class.
     *
     * @param string $key
     * @param string $value
     *
     * @return void
     */
    public function cache($key, $value);
}
